// <auto-generated />
using System;
using FitnesCenter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnesCenter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621122532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientService", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServicesId")
                        .HasColumnType("text");

                    b.HasKey("ClientsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ClientServices", (string)null);
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockerId")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Birthday = new DateOnly(1990, 5, 15),
                            Email = "ivan@example.com",
                            IsActive = true,
                            Name = "Иван",
                            Patronymic = "Алексеевич",
                            Phone = "+7-999-222-22-22",
                            Surname = "Петров",
                            TrainerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Birthday = new DateOnly(1985, 8, 20),
                            Email = "petr@example.com",
                            IsActive = true,
                            Name = "Петр",
                            Patronymic = "Иванович",
                            Phone = "+7-999-333-33-33",
                            Surname = "Сидоров"
                        });
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Lockers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2bd26d-6429-45af-84d2-17e6135f5c08"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("4ffeb940-cf64-433d-a263-efe39daf41aa"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("f18c859b-4b0b-4119-8d52-27ff79bcec08"),
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("546e7559-4f61-4d63-b848-a21f7d4f0abb"),
                            Number = 4
                        },
                        new
                        {
                            Id = new Guid("8607c335-37ac-4e37-b342-caf081c3206c"),
                            Number = 5
                        },
                        new
                        {
                            Id = new Guid("4c5ee02b-f560-433b-8e05-c02040f793d2"),
                            Number = 6
                        },
                        new
                        {
                            Id = new Guid("cbc55f31-c410-497c-9a43-fdf4f92f6b5a"),
                            Number = 7
                        },
                        new
                        {
                            Id = new Guid("6e5b62cc-2633-429c-96bd-fbfd1759ac97"),
                            Number = 8
                        },
                        new
                        {
                            Id = new Guid("41cd3c34-fbbb-4602-b4a1-842f8a12f857"),
                            Number = 9
                        },
                        new
                        {
                            Id = new Guid("8db55bea-fb46-4de9-80cf-4146db28e34b"),
                            Number = 10
                        },
                        new
                        {
                            Id = new Guid("a2141563-297c-44a0-807b-1e20cb16014e"),
                            Number = 11
                        },
                        new
                        {
                            Id = new Guid("176e5c8b-f3c8-44aa-9b14-5994eb29361c"),
                            Number = 12
                        },
                        new
                        {
                            Id = new Guid("2fadd572-18ae-4595-b275-0aa65dac5d6a"),
                            Number = 13
                        },
                        new
                        {
                            Id = new Guid("df5501e0-6396-4e11-87d7-ccf62e8ece0c"),
                            Number = 14
                        },
                        new
                        {
                            Id = new Guid("a127544d-0a72-44be-adbf-328faa6c09b8"),
                            Number = 15
                        },
                        new
                        {
                            Id = new Guid("f5a374b9-222f-4a62-8c54-e459bf339758"),
                            Number = 16
                        },
                        new
                        {
                            Id = new Guid("115feead-2df3-42f8-932a-d3ec78436457"),
                            Number = 17
                        },
                        new
                        {
                            Id = new Guid("f713318b-2db5-455e-b379-aba3e639abf5"),
                            Number = 18
                        },
                        new
                        {
                            Id = new Guid("05592c6c-fbdc-4062-98b8-f684d76466cc"),
                            Number = 19
                        },
                        new
                        {
                            Id = new Guid("adab007e-71ce-4030-8dc8-62b1e1674820"),
                            Number = 20
                        });
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = "SOLARIUM",
                            Name = "Солярий",
                            Price = 400
                        },
                        new
                        {
                            Id = "POOL",
                            Name = "Бассейн",
                            Price = 200
                        },
                        new
                        {
                            Id = "SAUNA",
                            Name = "Сауна",
                            Price = 0
                        },
                        new
                        {
                            Id = "CRYOSAUNA",
                            Name = "Криосауна",
                            Price = 1000
                        },
                        new
                        {
                            Id = "CROSSFIT",
                            Name = "Кроссфит",
                            Price = 500
                        });
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Алексей",
                            Patronymic = "Сергеевич",
                            Phone = "+7-999-111-11-11",
                            Status = 0,
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Мария",
                            Patronymic = "Ивановна",
                            Phone = "+7-999-444-44-44",
                            Status = 0,
                            Surname = "Петрова"
                        });
                });

            modelBuilder.Entity("ClientService", b =>
                {
                    b.HasOne("FitnesCenter.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesCenter.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Client", b =>
                {
                    b.HasOne("FitnesCenter.Domain.Entities.Locker", "Locker")
                        .WithOne("Client")
                        .HasForeignKey("FitnesCenter.Domain.Entities.Client", "LockerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnesCenter.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Clients")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Locker");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Locker", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnesCenter.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
